### ISSUE TITLE
Add return codes to the conductor

### ISSUE THREAD

**Issue by FrankD412** [LLNL/maestrowf#107]
The conductor currently terminates normally in all cases that it doesn't throw an exception. While this is useful for knowing that the conductor didn't error out, it's useless for using other scripts to know how a study terminated. This issue is intending to standardize a set of return codes that represent not only the normal termination of the conductor but to also assign codes for the termination of the study.

**Comment by kcathey** [comment]
Is this related to Pre & Post Steps (#98) and the mention it makes of return codes?

**Comment by FrankD412** [comment]
This issue is different -- the difference is as follows:

- Return codes for the conductor designate how the termination of the study itself occurred. So these are things like "terminated properly, all steps completed", or "terminated normally, but with failed steps", etc.
- Return codes for the pre and post steps dictate how the conductor should handle the step. These are return codes that tell the conductor to do things like "restart the step", "rerun the step from scratch", "mark the step as failed", etc. Those get assessed during status check time for any given step.

Hopefully, that clarifies the difference, @kcathey -- if not, keep throwing questions my way!. :-)

**Comment by kcathey** [comment]
@FrankD412 that clarifies it. Thanks!

**Comment by FrankD412** [comment]
@kcathey -- I've assigned this to myself because you're not listed as collaborator. I think I can add you as a Read only user since you're using forks.

**Comment by kcathey** [comment]
Completed with Pull Request #128
