### ISSUE TITLE
slurmscriptadapter.checkjobs: bytes and str

### ISSUE THREAD

**Issue by tadesautels** [LLNL/maestrowf#142]
In the snippet here:
        output, err = p.communicate()
        retcode = p.wait()

        status = {}
        for jobid in joblist:
            LOGGER.debug("Looking for jobid %s", jobid)
            status[jobid] = None

        if retcode == 0:
            for job in output.split("\n")[1:]:
...

The output variable is implicitly expected to be a str; if it's bytes, an error is thrown.

Recommend recasting output as follows:

        output, err = p.communicate()
        if not isinstance(output, str) and isinstance(output, bytes):
           output.decode("UTF-8")

**Comment by FrankD412** [comment]
@tadesautels -- Out of curiosity, you are running this in Python2.7?

**Comment by FrankD412** [comment]
Another accepted answer is to add `universal_newlines=True` to the `Popen` command. I'm going to test that one.

https://stackoverflow.com/questions/15374211/why-does-popen-communicate-return-bhi-n-instead-of-hi

**Comment by tadesautels** [comment]
The universal_newlines=True choice (which from 3.7 forward can be written as text=True, apparently) should do the trick, according to the docs.

I was running in Python3.x; when I tested the equivalent snippet (not the full Maestro code) in 2.7, there's no error, because "\n" and b"\n" are treated exactly the same. In 3.x, though, they're different, and you can't split a b"string" with a non-bytes string.

**Comment by tadesautels** [comment]
The general thrust of the changes looks good; out of curiosity, why did you go for universal_newlines=False, rather than universal_newlines=True?

**Comment by FrankD412** [comment]
Oh -- was it set to False? Let me go check. It should be True.
