### ISSUE TITLE
The enum34 module is not compatible with python3.6

### ISSUE THREAD

**Issue by koning** [LLNL/maestrowf#175]
The enum34 is a backport of the enum in python3.4 and should be limited to python versions less than python3.4.  In python3.6 installation of enum34 will cause an exception:
AttributeError: module 'enum' has no attribute 'IntFlag'

stackoverflow:
https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

**Comment by FrankD412** [comment]
@koning -- I've made `enum34` conditionally installed based on Python version, do you mind testing this to make sure it solves the issues you ran into?

**Comment by FrankD412** [comment]
Fixed by #176
