### ISSUE TITLE
Hooks for custom parameter generators in study specification

### ISSUE THREAD

**Issue by jwhite242** [LLNL/maestrowf#179]
Would be great to extend the self documenting/reproducible nature of the workflows to include the custom parameter generator.  Some dependency or something to specify the generator (or multiple generators), and perhaps some pgen parameters (separate from global.parameters) that could be used for arguments to the parameter generator.

**Comment by FrankD412** [comment]
I'm curious how multiple generators would work. @jwhite242 -- Any expectations on how this would work in a use case?

**Comment by jwhite242** [comment]
Having tried building a split tree type workflow in a single spec, i'm thinking multiple generators might actually be a bad idea.  That's probably adding too much complexity into the spec when that functionality would be better served by separate specs altogether (stitched together in a 'symphony').

**Comment by FrankD412** [comment]
I agree. A higher level driver is probably the better place to put something like that. I'm going to go ahead and close this issue. We can revisit this in the future.
