### ISSUE TITLE
Add the ability to map other data sources

### ISSUE THREAD

**Issue by jsemler** [LLNL/maestrowf#18]
We need the ability to map other data sources besides the YAML file to a Maestro workflow to support use cases such as building the spec programmatically or through a workflow builder tool.

**Comment by FrankD412** [comment]
@jsemler -- I was looking back at this issue and was wondering if you could expand on what you mean. I'm finding the description above to be kind of vague. Are you asking for interfaces for building the YAML specification in another manner? Or for having the ability to point to something like a study collection and selecting a pre-existing study?

**Comment by jsemler** [comment]
Sure! I was looking at generating a study via a Python interface. My initial use case was for prototyping a web application to create studies. I need some way to map data from a web form to Maestro.  I was initially thinking to maybe build the study object given the input data as I thought Maestro could create the study specification file.

**Comment by FrankD412** [comment]
I'm going to go ahead and close this -- we've not discussed this in some time. We can always file a new issue if this comes up again.
