### ISSUE TITLE
LocalScriptAdapter shell definition in batch requires shebang and quotes

### ISSUE THREAD

**Issue by koning** [LLNL/maestrowf#180]
The current LocalScriptAdapter takes an argument that is the shell including the shebang, shell="#!/bin/bash".  If a different shell is required, the shebang must be included when adding the the batch section.  In yaml this means that the variable needs to be quoted or it will be interpreted as a comment:
shell: "#!/bin/tcsh" 
not 
shell = #!/bin/tcsh <-- comment, shell will be empty
Removing the #! requirement and adding this when the script is written will eliminate the quoting requirement.

**Comment by FrankD412** [comment]
Fixed by #181
