### ISSUE TITLE
Python 2.x or 3.x

### ISSUE THREAD

**Issue by ssinji** [LLNL/maestrowf#185]
Python 3.x creates the following problem but 2.7 works fine for me.
Is this normal? or is this Conda virtual env problem?

Traceback (most recent call last):
  File "/anaconda3/bin/maestro", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/maestrowf/maestro.py", line 425, in main
    rc = args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'

**Comment by FrankD412** [comment]
Hi @ssinji -- Firstly, welcome and thanks for posting an issue. :)

So, I personally don't use a Conda install of Python, so it's great that you've posted this. Currently, I have TravisCI instances set up for Python 3.4, 3.5, and 3.6. I'm looking around and am not seeing anything obvious about what version Condas comes packaged with, so I'll keep digging.

Can you post the version output of your Python binary? My guess is that it's a 3.7 binary -- which might have made argparse changes (currently looking into that).

**Comment by ssinji** [comment]
Thanks for Right, it was Python 3.7. 
$ conda -V
conda 4.5.9

Thank you!

**Comment by ssinji** [comment]
Some more info: 
1) It seems python3.6 does not install maestro for the same reason
2) python 2.7 successfully installed maestro, but when running the example LULESH, it creates the following problem cloning Lulesh git hub


 2019-05-02 13:48:18,902 - maestrowf.datastructures.environment.gitdependency:acquire:171 - INFO - Cloning LULESH from https://github.com/LLNL/LULESH.git...
Traceback (most recent call last):
  File "/anaconda3/envs/maestro_test/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/anaconda3/envs/maestro_test/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/anaconda3/envs/maestro_test/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/anaconda3/envs/maestro_test/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file gitdependency.py, line 195
Traceback (most recent call last):
  File "/anaconda3/envs/maestro_test/lib/python2.7/logging/__init__.py", line 868, in emit
    msg = self.format(record)
  File "/anaconda3/envs/maestro_test/lib/python2.7/logging/__init__.py", line 741, in format
    return fmt.format(record)
  File "/anaconda3/envs/maestro_test/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/anaconda3/envs/maestro_test/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file gitdependency.py, line 195
2019-05-02 13:48:19,698 - maestrowf.datastructures.core.study:configure_study:389 - INFO -

It seems it is a string formatting issue. 

3) What is the python version you use for development? I would like to stick to the version that you use. Of course, I will use the python virtual env instead.

**Comment by FrankD412** [comment]
@ssinji -- I thought I had fixed the `GitDependency` logger bug, so useful to know that it's still there.

I use it locally with Python2.7 currently, and I checkout the repository and run `pip install .` from within the root of the repository.

I ran it locally and didn't get that error using develop. Are you strictly pip installing it?

**Comment by FrankD412** [comment]
@ssinji -- I just started a clean 3.7.3 virtual environment and ran the sample LULESH study specification without issue. The fact that you're using the specification leads me to believe that you're using the repository to install. What's the last commit when you run `git log`?

**Comment by eklee15** [comment]
@FrankD412 This user is the same user of @ssinji. I successfully ran the LULESH code. Thanks for your help. 

FYI, hope this helps your development. 
1. I'm using a develop git branch. 
commit b65ed469b1a3ccbf3551511ba5516a0e1c249f1a (HEAD -> develop, origin/develop, origin/HEAD)
Author: Francesco Di Natale <dinatale3@llnl.gov>
Date:   Wed May 1 14:30:15 2019 -0700

2. $ python --version
Python 2.7.16 :: Anaconda, Inc.

3. anaconda virtual environment.

**Comment by FrankD412** [comment]
@eklee15 -- No problem. I'm glad you got it working and thanks for the additional information.

Would you mind providing the version number for the virtual environment that was failing? I'm interested in seeing if I can track down why Maestro failed to launch on your initial environment. Thanks!

**Comment by eklee15** [comment]
@FrankD412 Sorry, I've already deleted the virtual environment and can't track the version. (I've updated numerous packages, which I don't remember) 

I will let you know if I experience the same problem later. 

You can close this issue. Thanks for your help.

**Comment by eklee15** [comment]
Oh, one more question. Do you have any example code for running LULLESH + maestro across multiple nodes/processes? I saw you have FLUX or SLURM adapter in tests/interfaces/scripts. Can you provide any example of how to use them?

**Comment by FrankD412** [comment]
@eklee15 - I don't currently have a sample of LULESH run across nodes, but I can try and get one up and running. If you have a more pressing deadline, feel free to email me (dinatale3@llnl.gov) and I can help you get set up.

**Comment by FrankD412** [comment]
@eklee15 -- I just committed a sample specification for SLURM and LULESH. Apologies for the delay. Just as a note, LULESH must be run across a cubic set of processors, so you have to use 3, 9, 27, etc. for the value of procs. You can find the sample spec here: https://github.com/LLNL/maestrowf/blob/develop/samples/lulesh/lulesh_sample1_unix_slurm.yaml

I'm going to go ahead and close this issue since that isn't it's focus. Feel free to start a new issue if you have other concerns, or reach me at my specified email. Thanks!
