### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'func'

### ISSUE THREAD

**Issue by chriswebster98** [LLNL/maestrowf#188]
When running maestro you can get the following error.
I am running Python 3.7.2 and my pip version is 19.1.1

**Comment by chriswebster98** [comment]
Jessica found a similar error and solution here: https://stackoverflow.com/questions/48648036/python-argparse-args-has-no-attribute-func

**Comment by FrankD412** [comment]
As @chriswebster98 mentioned, it looks like there's a bug in Python. It's a known bug in the python3's argparser library. https://bugs.python.org/issue16308
