### ISSUE TITLE
Unexpected Failed status

### ISSUE THREAD

**Issue by stewarthe6** [LLNL/maestrowf#194]
As far as I can tell, one of my scripts runs successfully and exits normally, Yet maestro says it failed.

[small_world_generate.log](https://github.com/LLNL/maestrowf/files/3570649/small_
[crawl.out.txt](https://github.com/LLNL/maestrowf/files/3570652/crawl.out.txt)
[Uploading crawl.slurm.sh.txt…]()
[small_world.yaml.txt](https://github.com/LLNL/maestrowf/files/3570654/small_world.yaml.txt)
[crawl.err.txt](https://github.com/LLNL/maestrowf/files/3570655/crawl.err.txt)

world_generate.log)

**Comment by FrankD412** [comment]
I worked with @stewarthe6 and it was a small error in the script that he was running. This issue is resolved.
