### ISSUE TITLE
Upload sdist to pypi

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/maestrowf#20]
For the version 1.0.0 release, you should have both the sdist and bdist versions available.

**Comment by FrankD412** [comment]
Good call, will look into this soon.

**Comment by FrankD412** [comment]
Uploaded an sdist and the py3 wheel. Located here: https://pypi.python.org/pypi/maestrowf/1.0.0

**Comment by FrankD412** [comment]
Uploaded an sdist and the py3 wheel. Located here: https://pypi.python.org/pypi/maestrowf/1.0.0

**Comment by IanLee1521** [comment]
New issue :)

We should set your setup.cfg file to build a universal (Python 2 & 3) wheel. 

I'll see about getting you a PR for that, but if you make a new issue and assignee to me, I will remember better.
