### ISSUE TITLE
Helper function

### ISSUE THREAD

**Issue by crkrenn** [LLNL/maestrowf#203]
To simplify the yaml spec for our workflows, it would be very helpful to have a function that would return a dictionary of all of the token:value pairs for a given run directory. 

@jsemler told me there is a yaml file that summarizes the token:value pairs for an complete workflow. 

But I think the function I describe would be of general utility.

**Comment by FrankD412** [comment]
@crkrenn -- Yeah, there's a metadata file that contains all the paths in a workspace. That would be the way to get the information after a study completes. You would need to write a script to parse the YAML to find the information after the fact, and then you'd be able to post process it however you  choose.

The functionality you're describing is in what I term as "funnel" steps. In that case, the step's dependency would contain something similar to `depends: [depends_step_*]`. That would make it such that if `depends_step`'s workspace is referenced using `$(depends_step.workspace)` in the step that uses the above depends, then the root directory containing all the combinations will be substituted.

**Comment by FrankD412** [comment]
@crkrenn -- My question is this: Is the functionality in my last comment what you're looking for or is this different? If you're on board with the functionality provided above, we should talk about its limitations. There are definitely cases where I would like to expand the above functionality.

**Comment by crkrenn** [comment]
I think I'm good now ;)
