### ISSUE TITLE
Docker hub?

### ISSUE THREAD

**Issue by joe-eklund** [LLNL/maestrowf#216]
I see in the docs that maestrowf is runnable in a docker container (very useful). This requires that you clone the repo and build the container yourself though.

Is it possible to add it to Docker hub? That way I could run it without having to build it and it would look a bit cleaner in my docker-compose.

It looks like there is an [llnl](https://hub.docker.com/u/llnl) docker hub user, but it doesn't seem to have many containers or any recent updates. Maybe @IanLee1521 knows how we could add an image to it?

**Comment by FrankD412** [comment]
That's a good idea, @joe-eklund! I'll look into it. If using the llnl user is preferred, then I'll do that -- waiting for Ian's response.

**Comment by FrankD412** [comment]
We now have a hub page up on the LLNL hub. I'll be adding an image soon.

https://hub.docker.com/r/llnl/maestro

**Comment by FrankD412** [comment]
Maestro is now on Docker Hub. Check it out [here](https://hub.docker.com/r/llnl/maestro). Closed.
