### ISSUE TITLE
The workspace reference in a restart step does not get string replaced

### ISSUE THREAD

**Issue by koning** [LLNL/maestrowf#217]
I am trying to write a restart step in Merlin that has a workspace reference in it but is not getting string replaced.

example step:
```
.
.
.
depends: [build]
restart: $(LAUNCHER) $(build.workspace)/mpi_hello $(V1) $(V2) > flux_run.out
nodes: 1
procs: 4
cores per task: 1
```

script:
```
#!/bin/bash
flux wreckrun -n 4 -N 1 -c 1 $(build.workspace)/mpi_hello 0.029187019936826375  0.030631498988624384 > flux_run.out
```

**Comment by FrankD412** [comment]
I haven't constructed a spec that confirms this, but looking through the code I can see where this can happen. I'll start looking into this soon.

**Comment by FrankD412** [comment]
@koning -- I've implemented what I think is a fix in the `bugfix/restart_ws` branch. Do you mind testing it?

**Comment by koning** [comment]
Yes this fixes the workspace issue, are there any other replacements I should try?

**Comment by FrankD412** [comment]
@koning -- The only other replacements I can think of are `$(WORKSPACE)` which is the moniker for referring to the local workspace. I expect that to work because that's quite literally the last thing I substitute in.

Please disregard my latest comment in PR #219 since you've tested it here.
