### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by dinatale2** [LLNL/maestrowf#22]
In order to help you test existing functionality and avoid regressions, a test suite should be introduced. There are testing platforms available for python (i.e. nose, unittest, etc.). Once the test suite runs, the next step is to set up CI. TravisCI is free and integrated with Github for instance, there's also other alternatives which are less integrated such as buildbot.

**Comment by FrankD412** [comment]
Moving this out of the Release 1.0.1 release.

**Comment by FrankD412** [comment]
We already have the basic TravisCI configuration running, not sure why this isn't closed yet. Closing.
