### ISSUE TITLE
possible logger bug

### ISSUE THREAD

**Issue by ben-bay** [LLNL/maestrowf#246]
When I was working with logger messages in `maestrowf/datastructures/yamlspecification.py`, the logger appeared to be broken. I was only able to view my `logger.warning` with a print.

**Comment by FrankD412** [comment]
Do you happen to have a reproducer for this handy? I'd like to take a look.

**Comment by ben-bay** [comment]
Reproducer, reproducer. I guess this is it: 

In #243, target a spec that has the key `frank_key` somewhere in one of the sections. Observe that there's no warning. Then use this version of `check_keys`, and you'll see the warning.
```

def check_keys(parent_key, section, valid_keys):
    diff = set(section.keys()).difference(set(valid_keys.keys()))
    for extra in diff:
            print("Unrecognized key '{0}' found in spec section '{1}'.".format(extra, parent_key))
    for key, val in section.items():
        if isinstance(val, dict) and key in valid_keys:
            check_keys(parent_key + "." + key, val, valid_keys[key])
```

**Comment by FrankD412** [comment]
Alright -- I just added dummy keys to a Maestro specification and no warnings showed up. That's odd considering that when Maestro is started the logger is definitely being configured. Marking as confirmed.
