### ISSUE TITLE
when using hashws, shouldn't the script names (e.g. slurm adapter) be hashed also?

### ISSUE THREAD

**Issue by jagreenough** [LLNL/maestrowf#267]
i have a use case with lots of variables for variation. we had to move to the hashed workspace option because the paths were too long.  i've run into a failure when using the hashed ws, that the script creation fails because it violates the 256 character limitation of file name length!  
if the dirs are hashed, shouldn't/couldn't the script names be hashed?  
i believe you already have a correspondence setup between steps names, workspaces and hash.  just use the hash for the script name.
Thanks!

**Comment by FrankD412** [comment]
@jagreenough -- Apologies, this one slipped by my memory. I re-encountered this when I was working on #291. I'm scoping out a fix for this in conjunction with the fix for @kallman2 's issue.

**Comment by jagreenough** [comment]
... this tells me who's got more 'juice', lol
