### ISSUE TITLE
YAMLSpecification Requires the batch entry to exist.

### ISSUE THREAD

**Issue by FrankD412** [LLNL/maestrowf#28]
The YAMLSpecification object currently has a hard requirement that the ```batch``` specification entry exist. The use case of running a workflow locally is also a valid one  and should be accounted for. There are two avenues for achieving this:
* Loosen the requirement that the ```batch``` entry must exist.
* Create a "local" adapter that runs all steps locally.

**Comment by jsemler** [comment]
I think Maestro will likely need an adaptor to run locally. Besides the batch configurations, there also needs to be a way to monitor the workflow that doesn't rely on a scheduler.

**Comment by FrankD412** [comment]
So currently, ScriptAdapters just execute and wait locally. I opted to make that the case because otherwise we'd be polling ```ps``` constantly. The local ScriptAdapter can override the parallel command and run it in the background possibly?

**Comment by FrankD412** [comment]
Fixed by #41
