### ISSUE TITLE
Access to packages from pgen

### ISSUE THREAD

**Issue by crkrenn** [LLNL/maestrowf#283]
Situation: 
1. I've written a pgen.py that depends on external packages (namely pandas, scipy, and sklearn): https://github.com/crkrenn/maestro_sheetmusic/blob/example/krenn1/multidimensional_sampling/multidimensional_sampling/pgen_sample.py
2. The only way I can get this to work is to install maestro into a virtual environment and to install the necessary packages on top of maestro. 

Concerns: 
1. Sharing this pgen.py with other people requires them to create their own installation of maestro. 
1. Combining multiple sets of python packages and tools will make this issue more complicated.

Question: 
1. At LLNL, we have a static global installation of maestro. Have you or will you consider mechanisms for pgen.py to access additional packages from either user or global directories when running the static version of maestro?

**Comment by FrankD412** [comment]
@crkrenn -- In order to pull in packages from the system Python install you would use the following:
```
python3 -m virtualenv --system-site-packages venv
```

That will make all the site packages are available. That would let you install Maestro on top of the system packages. It sounds like that's what you're looking for?

**Comment by crkrenn** [comment]
No, I want to `export PATH=$PATH:/usr/gapps/portal/bin`, then `maestro run -y --pgen ./pgen_sample.py sample_list.yaml`, and be able to `import sklearn` inside of `pgen_sample.py`.

The only solution that works now would be for every user to have their own maestro codetree and `venv`. And, if two users want to combine functionality based on a non-overlapping set of includes from two different pgen scripts, they need to update both `venv` trees. 

PS. For some reason on our system `python3 -m virtualenv venv` with python 3.6.4 throws an error for some packages, but `python3 -m venv venv` does not.

**Comment by FrankD412** [comment]
Tagging @jsemler and @jwhite242 to see if they have ways they've worked through this. From the sounds of it, this might require modifications to the the `$PYTHONPATH` variable in your environment to add a new set of site packages to be indexed for use. I'll have to do some more research into this and see if I can't find a solution. As it stands, I think this is less a Maestro bug and more of an environment set up issue -- I'll see what I can dig up.

**Comment by jwhite242** [comment]
So, I pretty much exclusively work in my own virtual environments.  The lone exception, which might work, is the way I've had to import visit: sys.path.append(<path to site-packages dir>).  Not sure if that's a great idea though vs the virtualenv approach.

Also, @crkrenn I've seen that virtualenv bug.  Seems like the public install of virtualenv is broken (their suggestion to pass it the full path to that, including that ridiculous spack hashing, to make it work isn't great..).  Have you tried using 3.7 instead?  I've not run into that bug with that python version yet.

**Comment by crkrenn** [comment]
@jwhite242, I'm trying to support ~20 end users ;). Some are fluent in python and venv. Some less so. I just found a package that lets you combine virtual environments. It's out of date, which could be a bad sign, or just that it was well written. https://github.com/jsvine/envplus

I also have only seen the virtualenv problem in python 3.6.4. It works fine in 3.7, but Jessica tells me that there are some compatibility problems with 3.7 and codepy. 

@FrankD412, I agree that it might be a deployment issue rather than a code base issue. Should we just tag it as such? Other sites would probably benefit from any solutions that you, @jsemler, or others come up with.

**Comment by FrankD412** [comment]
@ckrenn -- Yeah, I'll label it as a deployment issue and look into how we can layer a venv on top of the install.

**Comment by FrankD412** [comment]
@crkrenn -- I talked with @jsemler and we thought a good intermediate solution would be to deploy Maestro into your own supported virtual environment that you could use to maintain the packages you'd like your users to use. That would give you 100% control over your software stack and the scientific packages.
