### ISSUE TITLE
Allowing zero-like values as env variables

### ISSUE THREAD

**Issue by bryan-garcia** [LLNL/maestrowf#391]
### Discussed in https://github.com/LLNL/maestrowf/discussions/390

<div type='discussions-op-text'>

<sup>Originally posted by **bryan-garcia** April 29, 2022</sup>
Hi Everyone,

There is an issue when providing integer 0 or float 0 in the env.variables block that triggers a ValueError being raised. Specifically it's in [yamlspecification.py](https://github.com/LLNL/maestrowf/blob/develop/maestrowf/specification/yamlspecification.py) (method _verify_variables on line 190):
```python
if not value:
    msg = (
        "All variables must have a valid value. Empty strings "
        "are not allowed."
    )
    logger.error(msg)
    raise ValueError(msg)
```

A value of integer/float 0 in the env.variables block clearly triggers this error.

Sometimes I don't want to use the global.parameter block to define my values, and simply want an env variable. What are some thoughts for allowing this from a design perspective?</div>

**Comment by FrankD412** [comment]
Ah that is clearly an oversight -- yeah, the `not value` is a little too broad and catches the 0. That's a simple fix. For the other bit I'll pick this up in the discussion thread since I'm curious what the use case is.
