### ISSUE TITLE
URL in source license comment

### ISSUE THREAD

**Issue by gonsie** [LLNL/maestrowf#4]
The license comment in the source files is missing a URL. The text reads:
`# For details, see <URL describing code and how to download source>.`

This appears at least 39 times throughout the repo.

**Comment by FrankD412** [comment]
Good catch. I'll fix that here in a moment.

**Comment by FrankD412** [comment]
I only found 27 instances of the missing URL. Am I missing other similar style tags?

**Comment by gonsie** [comment]
My mistake, I was searching through 39 files, but only found 27 instances. You should be good!

**Comment by FrankD412** [comment]
Alright, master and develop are all fixed. Closing.
