### ISSUE TITLE
dynamic rate limiting of job submissions?

### ISSUE THREAD

**Issue by BenWibking** [LLNL/maestrowf#442]
On the cluster I'm using, there is a hard limit of 36 jobs per user that are running or pending in the SLURM queue.

However, I need to run a 200 parameter study. Is there any workaround for this other than splitting this large study up into studies of <= 36 parameters?

It would be ideal if it were possible for the conductor process to wait until jobs complete and then submit new jobs.

**Comment by BenWibking** [comment]
Following the route described in the docs here (https://maestrowf.readthedocs.io/en/latest/Maestro/how_to_guides/running_with_flux.html#launch-maestro-external-to-the-batch-jobflux-broker) seems like the best option for my use-case.

I've managed to install Flux via Spack on this cluser. The one remaining issue is that I have to wait until the SLURM job starts before I can do `maestro run` on the login node.

If I wanted to modify the Maestro conductor code so it polls SLURM to see whether the Flux broker job has started, how would I get started doing that?

**Comment by FrankD412** [comment]
Hi @BenWibking -- one thing to note is that `maestro run` also has a throttle option, you could limit the jobs to 36 there. Do keep in mind that is a universal limit between local and scheduled steps. So if you have a lot of local steps ahead of submitted steps, you will artificially limit yourself there.

**Comment by BenWibking** [comment]
> Hi @BenWibking -- one thing to note is that `maestro run` also has a throttle option, you could limit the jobs to 36 there. Do keep in mind that is a universal limit between local and scheduled steps. So if you have a lot of local steps ahead of submitted steps, you will artificially limit yourself there.

Adding `--throttle 36` solves the problem and works perfectly.

I was a bit thrown off by the wording in the documentation for the `--throttle` option. It might help to clarify that it refers to the total number of jobs in the (external, non-Maestro) scheduler queue (both running and pending), rather than only those that are actually executing.

**Comment by BenWibking** [comment]
I checked the status of this study today and it seems to have stopped submitting new jobs to SLURM. 

`maestro status` reports that several dozen steps are PENDING and dozens more are INITIALIZED, but nothing is in the SLURM queue. Maybe this is related to https://github.com/LLNL/maestrowf/issues/441?

This full log for this study is here: 
[medres_compressive.log.zip](https://github.com/LLNL/maestrowf/files/15213735/medres_compressive.log.zip)

**Comment by BenWibking** [comment]
This issue seems to be the same as #441, and that has more informative logs, so I'll close this.
