### ISSUE TITLE
Python 3: raw_input in maestrowf/maestro.py

### ISSUE THREAD

**Issue by wd15** [LLNL/maestrowf#47]
`raw_input` is not supported in Python 3. See, https://github.com/LLNL/maestrowf/blob/develop/maestrowf/maestro.py#L185

**Comment by dinatale2** [comment]
@FrankD412 `raw_input` was renamed to `input` in Python 3.

**Comment by FrankD412** [comment]
After some digging, it turns out that the package six has a method that will bridge compatibility.
```six.moves.input()``` has replaced the previous ```raw_input()``` call in maestro.py.
