### ISSUE TITLE
Rework the CLI to be more user friendly

### ISSUE THREAD

**Issue by FrankD412** [LLNL/maestrowf#53]
With the introduction of added functionality like checking study statuses, restarting studies, restarting failures, etc we need a cleaner interface for users. This ticket is meant to track discussion and ideas on new command line ideas.

My current thoughts are as follows:
```maestro run <study spec>```
```maestro status <study path>```
```maestro add <study path>```

Something to the above effect to enable an interface for allowing multiple studies to be run with the ability to add more studies and to construct compilations of studies.
@jsemler, @joe-eklund, @danlaney -- Thoughts?

**Comment by jsemler** [comment]
I like the proposed suggestions.

A few additional suggestions for discussion:

`maestro validate <study spec>`

The ability to easily validate a study spec without needing to setup the study would be helpful.

In regards to the restart functionality that is mentioned above. I think something like the following could be useful:

`maestro restart <optional step>`

I'm initially thinking two major use cases would be to have MaestroWF figure out where to restart a study or let a user specify a given step to restart from.

**Comment by FrankD412** [comment]
PR #63 is a start towards improving the CLI. It introduces ```run````, ```status```, and ```cancel``` to start. I'm going to move the comment left by @jsemler to its own issue as a further enhancement.
