### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by gonsie** [LLNL/maestrowf#89]
I'd like to start creating a documentation website... I think the doc strings can be easily imported into readthedocs or something similar.

Assign this one to me.

**Comment by gonsie** [comment]
Can you add a web hook
- [following these instructions](http://docs.readthedocs.io/en/latest/webhooks.html#github)
- with this payload URL: https://readthedocs.org/api/v2/webhook/maestrowf/32106/

I'll work on getting the content right.

**Comment by FrankD412** [comment]
Webhook added.
